### ISSUE TITLE
Implement fastPM as a gravity solver

### ISSUE THREAD

**Issue by maho3** [maho3/ltu-cmass#17]
The goal here is to write a new script `cmass/nbody/fastpm.py` which mirrors that of [`pmwd`](https://github.com/maho3/ltu-cmass/blob/main/cmass/nbody/pmwd.py) but instead uses [fastPM](https://github.com/fastpm/fastpm). It should allow configuration-based access to fastPM simulations. It should take a configuration and white noise field and then evolve and save the DM density and velocity fields.

**Comment by DeaglanBartlett** [comment]
I have provided a new nbody option which calls an already-existing FastPM executable to produce the relevant run. The outputs are processed to be stored in the same format as other gravity solvers. 

As with other gravity solvers, it can also handle replicating the Quijote initial conditions. See below for a comparison (power spectrum and cross correlation) of Quijote LH sim 0 and FastPM run with the same cosmology and ICs. I also plot a slice of the field, where we see good agreement.

<img width="1200" alt="fastpm_vs_quijote_pk" src="https://github.com/user-attachments/assets/30ec91b3-43aa-4b30-aed1-86a4d336ed3c">
<img width="682" alt="fastpm_vs_quijote_field" src="https://github.com/user-attachments/assets/d3170951-5c08-42ec-b65d-8ec55c71c406">

@maho3 This solver is not yet using MPI as none of the other methods appear to be yet. Do you have a method planned for how we will utilise MPI in ltu-cmass? If this is for a later to do, I can make a PR for this code.

**Comment by DeaglanBartlett** [comment]
As of 4b5a21c48899eca7b13ff546c88be75c81e95325, mpi is now available for FastPM. This follows the way it is called in https://github.com/fastpm/fastpm/blob/master/Examples/nbodykit.ipynb. Note that the user must ensure that mpirun in the conda environment is the same mpirun which mpicc used to compile FastPM.

The number of cores used is determined automatically. It is chosen as the smallest integer, $i$, up to and including `os.cpu_count()` for which $N \times B$ is exactly divisible by $i$, where $N$ is the grid size and $B$ is the Particle Mesh grid factor.

This now puts FastPM on the same footing as the other N-body codes. I will therefore submit a PR as I believe this issue has now been resolved.
