### ISSUE TITLE
Adopt #ili-summarizer for usage in #ltu-cmass

### ISSUE THREAD

**Issue by maho3** [maho3/ltu-cmass#3]
Currently, the ltu-cmass pipeline turns galaxy lightcones -> summaries using nbodykit and can only currently [do power spectra.](https://github.com/maho3/ltu-cmass/blob/main/cmass/summaries/Pk_nbkit.py)

The backend of [ili-summarizer](https://github.com/florpi/ili-summarizer/tree/main) is also in nbodykit, however it is primarily designed for halo catalogs in a comoving cube.

This project is to modify ili-summarizer to allow for lightcone galaxy catalogs.

**Definition of done**: 
- [ ]  New script(s) in [ltu-cmass/cmass/summaries](https://github.com/maho3/ltu-cmass/tree/main/cmass/summaries) which allow you to run ili-summarizer calculations

**Comment by laperezNYC** [comment]
Feb 26th Morning:
Matt to do: share the postprocessed lightcone with Lucia on infinity ; finishing config (of new light cones)
Lucia to do: get summarizer onto SF computer, figure out what updates it might need, look at how to power spectra example works

**Comment by tlmakinen** [comment]
Clarification: are we trying to remove the nbodykit dependency entirely ?

**Comment by maho3** [comment]
Nope :) Just to use nbodykit to access other summaries beyond Pk.
