### ISSUE TITLE
Adopt alpaga to ltu-cmass

### ISSUE THREAD

**Issue by maho3** [maho3/ltu-cmass#5]
The GPU-accelerated jaxlpt was recently deprecated in favor of [alpaga](https://bitbucket.org/aquila-consortium/alpaga/src/main/) (See Axel Lapel or Lucas Makinen for access.

This task is to update the ltu-cmass scripts which used jaxlpt to now use alpaga.

**Definition of done**:
- [ ] Removal of [jaxlpt](https://github.com/maho3/ltu-cmass/blob/main/cmass/nbody/jaxlpt.py)
- [ ] Replacement with an alpaga script

**Comment by tlmakinen** [comment]
happy to help with this -- I've got a branch which uses jax-cosmo's nonlinear Eisenstein-Hu matter power spectrum

**Comment by maho3** [comment]
Closed, as we now are only using the public BORG-LPT, or PM models.
