### ISSUE TITLE
Fix comoving -> peculiar velocities

### ISSUE THREAD

**Issue by maho3** [maho3/ltu-cmass#7]
In current comparisons with Quijote, it seems that the particle velocities output from pmwd and BORG are comoving velocities, not peculiar velocities as originally thought. The evidence for this has come from comparing halo catalogs with Quijote.

This task is to double-check this comparison and make sure we are using the right thing. For reference, the conversion goes as:

$$v_{\rm pec} = (1+z) v_{\rm com}$$ 

For the z=0 snapshots, this is the same, but for CMASS at z=0.5 if will be biased.

**Comment by DeaglanBartlett** [comment]
Looks like this is true, so I will add this correction

**Comment by DeaglanBartlett** [comment]
PR #9 solves this for Quijote. Still need to correct this for methods which call `rho_to_halo`.

**Comment by maho3** [comment]
This has been corrected in `cmass.nbody` models in the last couple commits.
